using System.Drawing;
using System.Linq;
using Content.Shared._Andromeda.Smelter;
using Content.Shared._Andromeda.Smelter.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.IoC;

namespace Content.Client._Andromeda.Smelter.UI;

[GenerateTypedNameReferences]
public sealed partial class SmelterMenu : DefaultWindow
{
    private const int AllCategoryId = -1;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<SmelterUiRecipeSelected>? OnSmelter;
    public event Action<string>? OnRecipeSelected;

    private List<SmelterUiRecipeSelected> _selectable = new();

    private SmelterUiRecipesState? _cachedState;
    private SmelterUiRecipeSelected? _selectedEntry;
    public SmelterMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SmelterButton.OnPressed += OnSmelterPressed;
    }

    private void UpdateRecipesVisibility()
    {
        if (_cachedState is null)
            return;

        RecipesContainer.RemoveAllChildren();

        var ItensGridContainer = new GridContainer();
        ItensGridContainer.Columns = 5;
        ItensGridContainer.VerticalExpand = true;

        RecipesContainer.AddChild(ItensGridContainer);
        AddRecipeListToGrid(_selectable, ItensGridContainer);

        if (_selectedEntry is not null && !_cachedState.Recipes.Contains(_selectedEntry.Value))
            RecipeSelectNull();
    }

    private void AddRecipeListToGrid(List<SmelterUiRecipeSelected> category, GridContainer gridContainer)
    {
        foreach (var entry in category)
        {
            if (!_prototype.TryIndex(entry.ProtoId, out var indexedEntry))
                continue;

            var control = new SmelterRecipeControl(entry);
            control.OnSelect += RecipeSelect;

            gridContainer.AddChild(control);
        }
    }

    public void UpdateState(SmelterUiRecipesState recipesState)
    {
        _cachedState = recipesState;
        CurrectSmeltFuelLabel.Text = Loc.GetString("smelter-fuel", ("CurrectFuelAmount", recipesState.CurrentFuelAmount), ("MaxFuelAmount", recipesState.MaxFuelAmount));
        var entManager = IoCManager.Resolve<IEntityManager>();
        MaterialsList.SetOwner(entManager.GetEntity(recipesState.Entity));
        _selectable.Clear();

        foreach (var entry in recipesState.Recipes)
        {
            if (!_prototype.TryIndex(entry.ProtoId, out var indexedEntry))
                continue;

            _selectable.Add(entry);
        }

        UpdateRecipesVisibility();
    }

    private void OnSmelterPressed(BaseButton.ButtonEventArgs _)
    {
        if (_selectedEntry is null)
            return;

        OnSmelter?.Invoke(_selectedEntry.Value);

        if(_cachedState is null)
            return;

        UpdateState(_cachedState);
    }

    private void RecipeSelect(SmelterUiRecipeSelected selected, SmelterRecipePrototype recipe)
    {
        _selectedEntry = selected;
        OnRecipeSelected?.Invoke(recipe.ID);

        var result = _prototype.Index(recipe.Result);
        var counter = recipe.ResultCount > 1 ? $" x{recipe.ResultCount}" : string.Empty;

        ItemView.SetPrototype(recipe.Result);
        ItemName.Text = result.Name + counter;
        ItemDescription.Text = result.Description;
        FuelRequirement.Text = Loc.GetString("smelter-fuel-needed", ("amount", recipe.FuelNeeded));

        SmelterButton.Disabled = !selected.Meltable;
    }

    private void RecipeSelectNull()
    {
        _selectedEntry = null;

        ItemView.SetPrototype(null);
        ItemName.Text = string.Empty;
        ItemDescription.Text = string.Empty;
        FuelRequirement.Text = string.Empty;
        SmelterButton.Disabled = true;
    }
}
