using Content.Shared._Andromeda.Smelter;
using Content.Shared._Andromeda.Smelter.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Andromeda.Smelter.UI;

[GenerateTypedNameReferences]
public sealed partial class SmelterRecipeControl : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<SmelterUiRecipeSelected, SmelterRecipePrototype>? OnSelect;

    private readonly SpriteSystem _sprite;

    private readonly SmelterRecipePrototype _recipePrototype;
    private readonly bool _meltable;
    private bool _highlight;

    public SmelterRecipeControl(SmelterUiRecipeSelected entry, bool highlight = false)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        _recipePrototype = _prototype.Index(entry.ProtoId);
        _meltable = entry.Meltable;
        _highlight = highlight;

        Button.OnPressed += _ => OnSelect?.Invoke(entry, _recipePrototype);

        UpdateView();
        UpdateColor();
    }

    public void SetHighlight(bool highlight)
    {
        _highlight = highlight;
        UpdateColor();
    }

    private void UpdateColor()
    {
        if (_highlight)
        {
            Button.ModulateSelfOverride = Color.FromHex("#53b58b");
            return;
        }

        if (!_meltable)
        {
            Button.ModulateSelfOverride = Color.FromHex("#1f2124");
            return;
        }

        Button.ModulateSelfOverride = null;
    }

    private void UpdateView()
    {
        View.SetPrototype(_recipePrototype.Result);
    }
}
