using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Andromeda.Millstone.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LabelledContent : BoxContainer
    {

        [DataField]
        public string? LabelText { get => Label.Text; set => Label.Text = value; }

        [DataField]
        public string? ButtonText { get => EjectButton.Text; set => EjectButton.Text = value; }

        [DataField]
        public bool ShowButton { get => EjectButton.Visible; set => EjectButton.Visible = value; }
    }
}
