using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Reagent;
using Content.Shared._Andromeda.Millstone;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Andromeda.Millstone.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class MillstoneMenu : FancyWindow
    {
        [Dependency] private readonly IEntityManager _entityManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        private readonly Dictionary<int, EntityUid> _chamberVisualContents = new();

        public event Action? OnGrind;
        public event Action? OnEjectAll;
        public event Action<EntityUid>? OnEjectChamber;

        public MillstoneMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            GrindButton.OnPressed += _ => OnGrind?.Invoke();

            ChamberContentBox.EjectButton.OnPressed += _ => OnEjectAll?.Invoke();

            ChamberContentBox.BoxContents.OnItemSelected += OnChamberBoxContentsItemSelected;
            BeakerContentBox.BoxContents.SelectMode = ItemList.ItemListSelectMode.None;
        }

        private void OnChamberBoxContentsItemSelected(ItemList.ItemListSelectedEventArgs args)
        {
            if (_chamberVisualContents.TryGetValue(args.ItemIndex, out var entity))
                OnEjectChamber?.Invoke(entity);
        }

        public void UpdateState(MillstoneInterfaceState state)
        {
            ChamberContentBox.EjectButton.Disabled = state.ChamberContents.Length <= 0;

            GrindButton.Disabled = !state.CanGrind;

            RefreshContentsDisplay(
                state.ReagentQuantities,
                _entityManager.GetEntityArray(state.ChamberContents));
        }

        public void HandleMessage(BoundUserInterfaceMessage message)
        {
            switch (message)
            {
                case MillstoneWorkStartedMessage workStarted:
                    SetWorkingVisuals();
                    break;

                case MillstoneWorkCompleteMessage:
                    ClearWorkingVisuals();
                    break;
            }
        }

        private void SetWorkingVisuals()
        {
            GrindButton.Disabled = true;

            ChamberContentBox.EjectButton.Disabled = true;
        }

        private void ClearWorkingVisuals()
        {
            GrindButton.Disabled = false;

            GrindButton.Modulate = Color.White;

            BeakerContentBox.EjectButton.Disabled = false;
        }

        private void RefreshContentsDisplay(
            IList<ReagentQuantity>? reagents,
            IReadOnlyList<EntityUid> containedSolids)
        {
            _chamberVisualContents.Clear();
            ChamberContentBox.BoxContents.Clear();

            foreach (var entity in containedSolids)
            {
                if (!_entityManager.EntityExists(entity))
                    continue;

                var sprite = _entityManager.GetComponent<SpriteComponent>(entity).Icon?.Default;
                var name = _entityManager.GetComponent<MetaDataComponent>(entity).EntityName;

                var item = ChamberContentBox.BoxContents.AddItem(name, sprite);
                _chamberVisualContents[ChamberContentBox.BoxContents.IndexOf(item)] = entity;
            }

            BeakerContentBox.BoxContents.Clear();

            if (reagents == null)
                return;

            if (reagents.Count == 0)
            {
                BeakerContentBox.BoxContents.AddItem(
                    Loc.GetString("millstone-menu-content-box-is-empty"));
                return;
            }

            foreach (var (reagent, quantity) in reagents)
            {
                var text = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto)
                    ? Loc.GetString("millstone-menu-content-entry", ("amount", quantity), ("name", proto.LocalizedName))
                    : "???";

                BeakerContentBox.BoxContents.AddItem(text);
            }
        }
    }
}
